# src: ./configs/ls-lint.yaml
# @(#) : ls-lint configuration for filename conventions
#
# Copyright (c) 2025 atsushifx <https://github.com/atsushifx>
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

ls:
  .dir: kebab-case | regex:^[@#.]?[a-z-_]+$
  .ts: kebab-case
  .type.ts: camelCase | PascalCase | regex:^[A-Z]{2,}[A-Za-z0-9]*$
  .class.ts: camelCase | PascalCase | regex:^[A-Z]{2,}[A-Za-z0-9]*$

  scripts:
    .*: kebab-case
    common:
      .*: kebab-case | PascalCase
    libs:
      .*: PascalCase
    tests:
      .*: PascalCase

  packages:
    .ts: kebab-case | camelCase | PascalCase
    .type.ts: camelCase | PascalCase | regex:^[A-Z]{2,}[A-Za-z0-9]*$
    .class.ts: camelCase | PascalCase | regex:^[A-Z]{2,}[A-Za-z0-9]*$
    shared:
      .ts: kebab-case | camelCase | PascalCase
      .type.ts: camelCase | PascalCase | regex:^[A-Z]{2,}[A-Za-z0-9]*$
      .class.ts: camelCase | PascalCase | regex:^[A-Z]{2,}[A-Za-z0-9]*$

# ignore directories
ignore:
  - "**/.git"
  - "**/.github"
  - "**/lib"
  - "**/module"
  - "**/node_modules"
  - "**/.textlint"
  - "**/.cache"
  - "**/.vscode"
